spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twest
    username: test
    password: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: test
